name: Sign and Create Attestations

on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
        description: "The image to sign and attest"

env:
  REGISTRY: ghcr.io

jobs:
  sign:
    name: Sign and Create Attestations
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write  # Required for OIDC signing
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Install Cosign
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.1.1

      # Sign the image with Cosign (using keyless signing)
      - name: Sign the image with keyless Cosign
        run: |
          cosign sign --yes ${{ inputs.image-name }}
        env:
          COSIGN_EXPERIMENTAL: 1

      # Verify the built-in SBOM attestation
      - name: Verify SBOM attestation
        run: |
          cosign verify-attestation --type spdx ${{ inputs.image-name }}
        env:
          COSIGN_EXPERIMENTAL: 1 