name: Scan with Trivy

on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
        description: "The image to scan with Trivy"

env:
  REGISTRY: ghcr.io

jobs:
  scan:
    name: Scan with Trivy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      security-events: write # For SARIF results
      pull-requests: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
      # Trivy scan
      - name: Run Trivy vulnerability scanner (HTML output)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ inputs.image-name }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          template: '@/contrib/html.tpl'
          output: 'trivy-results.html'
          
      # Generate SARIF report for GitHub Security tab
      - name: Run Trivy vulnerability scanner (SARIF output)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ inputs.image-name }}
          format: 'sarif'
          exit-code: '1' 
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL'
          output: 'trivy-results.sarif'
          
      # Upload Trivy scan results to GitHub Security tab
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
          category: 'trivy'
          
      # Post Trivy scan results as PR comment
      - name: Post Trivy scan results as PR comment
        if: github.event_name == 'pull_request'
        uses: thollander/actions-comment-pull-request@v3
        with:
          filePath: trivy-results.html
          comment_tag: trivy-scan-results
          
      - name: Upload Trivy scan results as artifact  
        uses: actions/upload-artifact@v4
        with:
          name: trivy-results
          path: trivy-results.sarif 